# Dependencies
markdown:         GFM
highlighter:      rouge

# Permalinks
permalink:        pretty


# Setup
title:            Nivethitha S
tagline:          'Software Developer'
description:      'Software Developer'
url:              https://nivi.dev
baseurl:          https://nivi.dev/

author:
  name:           'Nivethitha'
  url:            https://github.com/nivitvr

gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/nivitvr/nivitvr.github.io
